(package "yascroll"
         "0.2.0"
         "Yet Another Scroll Bar Mode")

(website-url "https://github.com/emacsorphanage/yascroll")
(keywords "convenience")

(package-file "yascroll.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "melpa")

(depends-on "emacs" "26.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
